#  docker run -d -p 3306:3306 -v ~/Documents/java/spring5-recipe-app/dockerfiles/mysql/prod/etc/mysql/:/etc/mysql/conf.d -v ~/Documents/java/spring5-recipe-app/dockerfiles/mysql/prod/var/lib/mysql:/var/lib/mysql --name mysql-prod-image -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=sfg_prod -e MYSQL_USER=sfg_prod_user -e MYSQL_PASSWORD=123 mysql:latest

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false