# docker run -d -p 3306:3306 -v ~/Documents/java/spring5-recipe-app/dockerfiles/mysql/etc/mysql/:/etc/mysql/conf.d -v ~/Documents/java/spring5-recipe-app/dockerfiles/mysql/var/lib/mysql:/var/lib/mysql --name mysql-developer-image -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=sfg_dev -e MYSQL_USER=sfg_dev_user -e MYSQL_PASSWORD=123 mysql:latest
# select id, cook_time, description, difficulty, prep_time, servings from recipe where id=1;

spring:
  datasource:
    
    platform: mysql
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

